// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArqmR6D6zMBzY-y8VzyXdiZ6KnCZLo2jM',
    appId: '1:697562482997:web:989326b5c6de2cbf78247c',
    messagingSenderId: '697562482997',
    projectId: 'hackathonapp-7d5c8',
    authDomain: 'hackathonapp-7d5c8.firebaseapp.com',
    storageBucket: 'hackathonapp-7d5c8.appspot.com',
    measurementId: 'G-3G9C1VHG4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDToVOhjSy7QOXUsufobec6zRZdlq2zahM',
    appId: '1:697562482997:android:9349d1588791d1d178247c',
    messagingSenderId: '697562482997',
    projectId: 'hackathonapp-7d5c8',
    storageBucket: 'hackathonapp-7d5c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCre7G84YL-Bi49wU9kTIJmpEwoC8Zz0bE',
    appId: '1:697562482997:ios:49208d6acffe9cf578247c',
    messagingSenderId: '697562482997',
    projectId: 'hackathonapp-7d5c8',
    storageBucket: 'hackathonapp-7d5c8.appspot.com',
    iosBundleId: 'com.example.myapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArqmR6D6zMBzY-y8VzyXdiZ6KnCZLo2jM',
    appId: '1:697562482997:web:ded449628275353678247c',
    messagingSenderId: '697562482997',
    projectId: 'hackathonapp-7d5c8',
    authDomain: 'hackathonapp-7d5c8.firebaseapp.com',
    storageBucket: 'hackathonapp-7d5c8.appspot.com',
    measurementId: 'G-CZCTJKWXXT',
  );
}
